FROM --platform=linux/amd64 golang:1.17-alpine AS builder
RUN apk add git g++ fuse
COPY . /seaweed
WORKDIR /seaweed
RUN cd ./weed; CGO_ENABLED=0 go mod tidy
RUN cd ./weed; CGO_ENABLED=0 go build -ldflags "-extldflags -static"

FROM  --platform=linux/amd64 alpine AS final
LABEL author="Chris Lu"
COPY --from=builder /seaweed/weed/weed /usr/bin/
RUN mkdir -p /etc/seaweedfs
COPY --from=builder /seaweed/docker/filer.toml /etc/seaweedfs/filer.toml
COPY --from=builder /seaweed/docker/entrypoint.sh /entrypoint.sh
RUN apk add fuse 

# volume server gprc port
EXPOSE 18080
# volume server http port
EXPOSE 8080
# filer server gprc port
EXPOSE 18888
# filer server http port
EXPOSE 8888
# master server shared gprc port
EXPOSE 19333
# master server shared http port
EXPOSE 9333
# s3 server http port
EXPOSE 8333
# webdav server http port
EXPOSE 7333

RUN mkdir -p /data/filerldb2

VOLUME /data
WORKDIR /data

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
